### ISSUE TITLE
Integrations Checklist

### ISSUE THREAD

**Issue by BrandonRomano** [BrandonRomano/waypoint#2]
- [x] docker
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/docker)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/docker)
- [x] docker-pull
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/docker/pull)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/docker#docker-pull-builder)
- [x] docker-ref
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/docker/ref)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/docker#docker-ref-builder)
- [x] aws-alb
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/alb)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-ec2#aws-alb-releasemanager)
- [x] aws-ami
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/ami)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-ec2#aws-ami-builder)
- [x] aws-ec2
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/ec2)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-ec2)
- [x] aws-ecr
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/ecr)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-ecs#aws-ecr-registry)
- [x] aws-ecr-pull 
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/ecr/pull)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-lambda#aws-ecr-pull-builder)
- [x] aws-ecs
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/ecs)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-ecs)
- [x] aws-lambda
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/lambda)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-lambda)
- [x] lambda-function-url
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/lambda/function_url)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-lambda#lambda-function-url-releasemanager)
- [x] aws-ssm
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/aws/ssm)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/aws-ssm)
- [x] azure-container-instance
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/azure/aci)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/azure-container-instance)
- [x] consul
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/consul)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/consul)
- [x] exec
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/exec)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/exec)
- [x] files
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/files)
  - ~Docs in DevDot~
- [x] google-cloud-run
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/google/cloudrun)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/google-cloud-run)
- [x] kubernetes
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/k8s)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/kubernetes)
- [x] kubernetes-apply
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/k8s/apply)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/kubernetes#kubernetes-apply-platform)
- [x] helm
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/k8s/helm)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/helm)
- [x] nomad
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/nomad)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/nomad)
- [x] nomad-jobspec
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/nomad/jobspec)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/nomad#nomad-jobspec-platform)
- [x] nomad-jobspec-canary
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/nomad/canary)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/nomad#nomad-jobspec-canary-releasemanager)
- [x] null
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/null)
  - ~Docs in DevDot~
- [x] pack
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/pack)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/pack)
- [x] terraform-cloud
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/tfc)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/terraform-cloud)
- [x] vault
  - [Folder](https://github.com/BrandonRomano/waypoint/tree/main/builtin/vault)
  - [Docs in DevDot](https://developer.hashicorp.com/waypoint/plugins/vault)
